[package]
name = "hello"
version = "0.1.0"
authors = ["Jack Drogon <jack.xsuperman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raft = { version = "0.6.0-alpha", default-features = false }
