#!/bin/bash

if [ "$#" -eq 0 ]
then
	echo "run ${0} project_name"
	exit 1
fi

PROJECT=${1}
DIR="codebase  inspect  library  pattern  performance  practice  syntax  test  tools"

for dir in ${DIR}; do
	echo "${PROJECT}/${dir}"
	mkdir -p "${PROJECT}/${dir}"
done
