[package]
name = "arrow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "record_batch"
path = "src/bin/record_batch.rs"

[[bin]]
name = "data_type"
path = "src/bin/data_type.rs"

[dependencies]
arrow-array = "49.0.0"
arrow-schema = "49.0.0"
