[package]
name = "clap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.27.0"

[[bin]]
name = "clap_sample"
path = "src/clap_sample.rs"
