[package]
name = "anyhow-ex"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "context"
path = "src/context.rs"

[dependencies]
anyhow = "1.0"
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0.117"
